"""
Live trading module — Ashish Capital Scanner (Dhan version).

Identical strategy logic to trade.py (M-stock version) but uses
Dhan's SDK for order placement. Key advantages over M-stock:
  - No daily login/TOTP in this module — access token is pre-generated
    by dhan_token_refresh.py which runs at 8:45 AM IST daily
  - IP is whitelisted automatically by dhan_token_refresh.py
  - Runs fully from GitHub Actions — no PC needed during market hours

Strategy:
  Layer 1 — Scanner qualification (Elite Compounder OR OBV+RS Combo)
  Layer 2 — Weekly ST(10,3) AND Daily ST(10,3) both bullish
  Layer 3 — Entry: Daily ST(2,1) bullish crossover
  Exit    — Daily ST(10,3) bearish crossover OR 10% hard stop-loss

Capital:
  Elite portfolio : Rs 50,000, max 5 positions, ~Rs 10,000 each
  OBV/RS portfolio: Rs 50,000, max 5 positions, ~Rs 10,000 each

Order type: CNC (delivery)
"""

import datetime
import json
import logging
import math
import os
import time

import pandas as pd
import requests
from dhanhq import DhanContext, dhanhq
from dhan_data import DhanData

import config
from market_hours import is_within_trading_window
from supertrend import get_supertrend_state

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

ELITE_BUDGET       = 50_000
COMBO_BUDGET       = 50_000
MAX_POSITION_VALUE = 20_000
TARGET_POSITION    = 10_000
MAX_POSITIONS      = 5
STOP_LOSS_PCT      = 0.10

ST_SLOW_PERIOD = 10; ST_SLOW_MULT = 3.0
ST_FAST_PERIOD = 2;  ST_FAST_MULT = 1.0

# ---------------------------------------------------------------------------
# Dhan client initialisation
# ---------------------------------------------------------------------------

def get_dhan_client() -> dhanhq | None:
    """
    Returns a ready-to-use dhanhq client using the access token
    pre-generated by dhan_token_refresh.py (stored as DHAN_ACCESS_TOKEN).
    No login or TOTP needed here — the refresh workflow handles that.
    """
    client_id    = os.environ.get("DHAN_CLIENT_ID", "")
    access_token = os.environ.get("DHAN_ACCESS_TOKEN", "")

    if not client_id or not access_token:
        logger.error(
            "trade_dhan: DHAN_CLIENT_ID or DHAN_ACCESS_TOKEN missing. "
            "Has dhan_token_refresh workflow run today?"
        )
        _send_alert(
            "⚠️ *Dhan trade cycle skipped*\n"
            "`DHAN_ACCESS_TOKEN` is missing.\n"
            "Check that the token refresh workflow ran at 8:45 AM IST."
        )
        return None

    try:
        ctx = DhanContext(client_id, access_token)
        client = dhanhq(ctx)
        logger.info("trade_dhan: Dhan client initialised")
        return client
    except Exception as exc:
        logger.error("trade_dhan: client init failed: %s", exc)
        return None


# ---------------------------------------------------------------------------
# Security ID lookup (Dhan uses numeric security_id, not ticker symbols)
# ---------------------------------------------------------------------------

_SECURITY_ID_CACHE: dict[str, str] = {}


def get_security_id(symbol: str, client: dhanhq) -> str | None:
    """
    Looks up Dhan's numeric security_id for a given NSE symbol.
    Dhan requires security_id (e.g. '1333' for HDFC Bank) rather than
    ticker symbol for order placement and market data calls.
    Uses the compact security list CSV, cached in memory per run.
    """
    global _SECURITY_ID_CACHE

    if symbol in _SECURITY_ID_CACHE:
        return _SECURITY_ID_CACHE[symbol]

    # Load security list on first call
    if not _SECURITY_ID_CACHE:
        try:
            import urllib.request
            url = dhanhq.COMPACT_CSV_URL
            with urllib.request.urlopen(url, timeout=30) as resp:
                import csv, io
                content = resp.read().decode("utf-8")
                reader = csv.DictReader(io.StringIO(content))
                for row in reader:
                    # Dhan CSV columns: SEM_SMST_SECURITY_ID, SEM_TRADING_SYMBOL, SEM_EXM_EXCH_ID
                    if row.get("SEM_EXM_EXCH_ID") == "NSE":
                        sym = row.get("SEM_TRADING_SYMBOL", "").upper().strip()
                        sid = row.get("SEM_SMST_SECURITY_ID", "").strip()
                        if sym and sid:
                            _SECURITY_ID_CACHE[sym] = sid
            logger.info("trade_dhan: loaded %d NSE security IDs", len(_SECURITY_ID_CACHE))
        except Exception as exc:
            logger.error("trade_dhan: security list load failed: %s", exc)
            return None

    sid = _SECURITY_ID_CACHE.get(symbol)
    if not sid:
        logger.warning("trade_dhan: no security_id found for %s", symbol)
    return sid


# ---------------------------------------------------------------------------
# Market data
# ---------------------------------------------------------------------------

def get_ltp(symbol: str, client: dhanhq) -> float | None:
    """Returns last traded price for a single NSE symbol."""
    sid = get_security_id(symbol, client)
    if not sid:
        return None
    try:
        resp = client.ticker_data({"NSE_EQ": [int(sid)]})
        data = resp.get("data", {})
        # Response: {"NSE_EQ": {"<sid>": {"last_price": ...}}}
        nse_data = data.get("NSE_EQ", {})
        item = nse_data.get(str(sid)) or nse_data.get(sid) or {}
        ltp = item.get("last_price") or item.get("LTP")
        return float(ltp) if ltp else None
    except Exception as exc:
        logger.debug("trade_dhan: get_ltp(%s) failed: %s", symbol, exc)
        return None


def get_holdings(client: dhanhq) -> dict[str, dict]:
    """Returns CNC holdings as {ticker: {qty, avg_price, ltp}}."""
    try:
        resp = client.get_holdings()
        holdings = {}
        for item in (resp.get("data") or []):
            symbol = (item.get("tradingSymbol") or "").upper().strip()
            if not symbol:
                continue
            holdings[symbol] = {
                "qty":       int(item.get("totalQty", 0)),
                "avg_price": float(item.get("avgCostPrice", 0)),
                "ltp":       float(item.get("lastTradedPrice", 0)),
            }
        return holdings
    except Exception as exc:
        logger.error("trade_dhan: get_holdings failed: %s", exc)
        return {}


# ---------------------------------------------------------------------------
# Order placement
# ---------------------------------------------------------------------------

def place_order(symbol: str, qty: int, transaction_type: str,
                client: dhanhq) -> dict:
    """Places a CNC market order via Dhan SDK."""
    sid = get_security_id(symbol, client)
    if not sid:
        raise ValueError(f"No security_id found for {symbol}")

    logger.info("trade_dhan: placing %s %s x%d CNC MARKET (sid=%s)",
                transaction_type, symbol, qty, sid)

    resp = client.place_order(
        security_id=sid,
        exchange_segment=dhanhq.NSE,
        transaction_type=dhanhq.BUY if transaction_type == "BUY" else dhanhq.SELL,
        quantity=qty,
        order_type=dhanhq.MARKET,
        product_type=dhanhq.CNC,
        price=0,
        tag="AshishScanner",
    )
    logger.info("trade_dhan: order response: %s", resp)
    return resp


# ---------------------------------------------------------------------------
# Trade state persistence
# ---------------------------------------------------------------------------

def _load_state() -> dict:
    path = config.TRADE_STATE_PATH
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return {"elite": {}, "combo": {}}


def _save_state(state: dict) -> None:
    os.makedirs("cache", exist_ok=True)
    with open(config.TRADE_STATE_PATH, "w") as f:
        json.dump(state, f, indent=2)


# ---------------------------------------------------------------------------
# Qualified stock list
# ---------------------------------------------------------------------------

def get_qualified_stocks() -> dict[str, list[str]]:
    csv_path = config.TRADE_QUALIFIED_CSV_PATH
    if not os.path.exists(csv_path):
        logger.warning("trade_dhan: qualified CSV not found at %s", csv_path)
        return {"elite": [], "combo": []}
    try:
        df = pd.read_csv(csv_path)
        df["ticker"] = df["ticker"].str.replace(r"\.NS$", "", regex=True).str.upper()
        elite = df[df["EliteCompounderScore"] >= 65].sort_values(
            "EliteCompounderScore", ascending=False)["ticker"].tolist()
        combo_mask = (
            df["obv_leadership_rank"].notna() & (df["obv_leadership_rank"] > 90) &
            df["rs_rank"].notna() & (df["rs_rank"] > 90)
        )
        combo = df[combo_mask].copy()
        combo["combo_rank"] = (combo["obv_leadership_rank"] + combo["rs_rank"]) / 2
        combo = combo.sort_values("combo_rank", ascending=False)["ticker"].tolist()
        logger.info("trade_dhan: qualified — elite: %d, combo: %d", len(elite), len(combo))
        return {"elite": elite, "combo": combo}
    except Exception as exc:
        logger.error("trade_dhan: failed to read qualified CSV: %s", exc)
        return {"elite": [], "combo": []}


# ---------------------------------------------------------------------------
# Supertrend checks
# ---------------------------------------------------------------------------

# Data fetching now uses Dhan API via DhanData (replaces yfinance).
# DhanData instance is created per trade cycle in run_trade_cycle()
# and passed into check_supertrend_conditions via a module-level reference.
_dhan_data: DhanData | None = None


def check_supertrend_conditions(symbol: str) -> dict:
    result = {
        "weekly_10_3_bullish": None, "daily_10_3_bullish": None,
        "daily_10_3_cross_down": False, "daily_2_1_cross_up": False,
        "eligible_for_entry": False, "error": None,
    }
    if _dhan_data is None:
        result["error"] = "DhanData not initialised"
        return result

    weekly_df = _dhan_data.get_weekly(symbol, weeks=104)
    if weekly_df is None or len(weekly_df) < 15:
        result["error"] = "insufficient weekly data"
        return result
    result["weekly_10_3_bullish"] = get_supertrend_state(
        weekly_df, ST_SLOW_PERIOD, ST_SLOW_MULT)["bullish"]

    time.sleep(0.15)  # micro-throttle between internal Data API calls

    daily_df = _dhan_data.get_daily(symbol, days=400)
    if daily_df is None or len(daily_df) < 15:
        result["error"] = "insufficient daily data"
        return result
    slow = get_supertrend_state(daily_df, ST_SLOW_PERIOD, ST_SLOW_MULT, prefix="d10_")
    fast = get_supertrend_state(daily_df, ST_FAST_PERIOD, ST_FAST_MULT, prefix="d2_")
    result["daily_10_3_bullish"]    = slow["bullish"]
    result["daily_10_3_cross_down"] = slow["cross_down"]
    result["daily_2_1_cross_up"]    = fast["cross_up"]
    result["eligible_for_entry"]    = bool(
        result["weekly_10_3_bullish"] and result["daily_10_3_bullish"])
    return result


# ---------------------------------------------------------------------------
# Position sizing
# ---------------------------------------------------------------------------

def compute_qty(price: float) -> int:
    if price <= 0:
        return 0
    qty = max(1, math.floor(TARGET_POSITION / price))
    if qty * price > MAX_POSITION_VALUE:
        logger.warning("trade_dhan: 1 share (Rs %.0f) exceeds MAX_POSITION_VALUE", price)
    return qty


# ---------------------------------------------------------------------------
# Telegram alerts
# ---------------------------------------------------------------------------

def _send_alert(message: str) -> None:
    token   = os.environ.get("TELEGRAM_BOT_TOKEN", "")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID", "")
    if not token or not chat_id:
        return
    try:
        requests.post(
            f"https://api.telegram.org/bot{token}/sendMessage",
            json={"chat_id": chat_id, "text": message, "parse_mode": "Markdown"},
            timeout=10,
        )
    except Exception as exc:
        logger.debug("trade_dhan: Telegram failed: %s", exc)


def _entry_alert(symbol: str, strategy: str, qty: int, price: float, st: dict) -> None:
    w = "✅" if st.get("weekly_10_3_bullish") else "❌"
    d = "✅" if st.get("daily_10_3_bullish")  else "❌"
    _send_alert(
        f"🟢 *ENTRY — {symbol}*\n"
        f"Strategy : {strategy}\n"
        f"Signal   : ST(2,1) bullish crossover\n"
        f"Price    : ₹{price:,.2f}\n"
        f"Qty      : {qty} shares (~₹{qty*price:,.0f})\n"
        f"Filters  : {w} Weekly ST(10,3) | {d} Daily ST(10,3)\n"
        f"Order    : *BUY {qty} {symbol} CNC MARKET — placed via Dhan*"
    )


def _exit_alert(symbol: str, strategy: str, qty: int,
                entry_price: float, exit_price: float, reason: str) -> None:
    pnl     = (exit_price - entry_price) * qty
    pnl_pct = (exit_price - entry_price) / entry_price * 100
    emoji   = "🟩" if pnl >= 0 else "🟥"
    _send_alert(
        f"🔴 *EXIT — {symbol}*\n"
        f"Strategy : {strategy}\n"
        f"Reason   : {reason}\n"
        f"Entry    : ₹{entry_price:,.2f} → Exit: ₹{exit_price:,.2f}\n"
        f"P&L      : {emoji} ₹{pnl:+,.0f} ({pnl_pct:+.1f}%) on {qty} shares\n"
        f"Order    : *SELL {qty} {symbol} CNC MARKET — placed via Dhan*"
    )


def _cycle_summary(state: dict) -> None:
    now_ist = datetime.datetime.utcnow() + datetime.timedelta(hours=5, minutes=30)
    _send_alert(
        f"📊 *Dhan trade cycle — {now_ist.strftime('%H:%M IST')}*\n"
        f"Elite : {len(state.get('elite', {}))}/{MAX_POSITIONS} positions\n"
        f"Combo : {len(state.get('combo', {}))}/{MAX_POSITIONS} positions"
    )


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def run_trade_cycle() -> None:
    logger.info("trade_dhan: === starting cycle %s UTC ===",
                datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M"))

    # GitHub Actions cron triggers can fire late (queue delays). If this
    # run woke up outside the actual trading window, bail out before any
    # API calls or Telegram alerts — a delayed cron should be a no-op.
    if not is_within_trading_window():
        return

    global _dhan_data
    client = get_dhan_client()
    if client is None:
        return

    # Initialise shared Dhan data layer — used by check_supertrend_conditions
    _dhan_data = DhanData(client)

    state     = _load_state()
    holdings  = get_holdings(client)
    qualified = get_qualified_stocks()

    strategy_map = {
        "elite": {"stocks": qualified.get("elite", []), "label": "Elite Compounder"},
        "combo": {"stocks": qualified.get("combo", []), "label": "OBV/RS Combo"},
    }

    for strat_key, strat in strategy_map.items():
        open_positions = state.setdefault(strat_key, {})
        qualified_set  = set(strat["stocks"])

        # --- Exits ---
        for symbol, pos in list(open_positions.items()):
            entry_price = pos["entry_price"]
            qty         = pos["qty"]
            ltp = _dhan_data.get_ltp(symbol) or holdings.get(symbol, {}).get("ltp")
            if ltp is None:
                continue

            # Hard stop-loss
            if ltp <= entry_price * (1 - STOP_LOSS_PCT):
                logger.info("trade_dhan: STOP LOSS %s", symbol)
                try:
                    place_order(symbol, qty, "SELL", client)
                except Exception as exc:
                    logger.error("trade_dhan: SELL failed %s: %s", symbol, exc)
                _exit_alert(symbol, strat["label"], qty, entry_price, ltp,
                            f"Hard stop-loss ({STOP_LOSS_PCT*100:.0f}%)")
                del open_positions[symbol]
                continue

            # ST(10,3) bearish crossover
            st = check_supertrend_conditions(symbol)
            if st.get("daily_10_3_cross_down"):
                logger.info("trade_dhan: ST(10,3) EXIT %s", symbol)
                try:
                    place_order(symbol, qty, "SELL", client)
                except Exception as exc:
                    logger.error("trade_dhan: SELL failed %s: %s", symbol, exc)
                _exit_alert(symbol, strat["label"], qty, entry_price, ltp,
                            "Daily ST(10,3) bearish crossover")
                del open_positions[symbol]
                continue

            # Dropped off scanner list
            if symbol not in qualified_set:
                logger.info("trade_dhan: %s dropped off qualified list", symbol)
                try:
                    place_order(symbol, qty, "SELL", client)
                except Exception as exc:
                    logger.error("trade_dhan: SELL failed %s: %s", symbol, exc)
                _exit_alert(symbol, strat["label"], qty, entry_price, ltp,
                            "Dropped off scanner qualified list")
                del open_positions[symbol]

        # --- Entries ---
        if len(open_positions) >= MAX_POSITIONS:
            state[strat_key] = open_positions
            continue

        candidates = [s for s in strat["stocks"] if s not in open_positions]
        other_strat = "combo" if strat_key == "elite" else "elite"
        _error_counts: dict[str, int] = {}

        for symbol in candidates:
            if len(open_positions) >= MAX_POSITIONS:
                break
            if symbol in state.get(other_strat, {}):
                continue

            ltp = _dhan_data.get_ltp(symbol)
            if ltp is None:
                _error_counts["no_ltp"] = _error_counts.get("no_ltp", 0) + 1
                continue

            st = check_supertrend_conditions(symbol)
            time.sleep(0.3)  # throttle — Dhan Data APIs cap at 5 req/sec;
                              # each check makes 2 calls (weekly+daily), so
                              # without this, scanning many candidates back
                              # to back can silently hit the rate limit and
                              # look identical to a real data-fetch failure
            if st.get("error"):
                _error_counts[st["error"]] = _error_counts.get(st["error"], 0) + 1
                continue
            if not st.get("eligible_for_entry"):
                _error_counts["not_eligible"] = _error_counts.get("not_eligible", 0) + 1
                continue
            if not st.get("daily_2_1_cross_up"):
                _error_counts["no_cross_up"] = _error_counts.get("no_cross_up", 0) + 1
                continue

            qty = compute_qty(ltp)
            if qty == 0:
                continue

            logger.info("trade_dhan: ENTRY %s qty=%d @ Rs %.2f", symbol, qty, ltp)
            try:
                place_order(symbol, qty, "BUY", client)
                open_positions[symbol] = {
                    "qty": qty, "entry_price": ltp,
                    "entry_date": datetime.date.today().isoformat(),
                    "strategy": strat_key,
                }
                _entry_alert(symbol, strat["label"], qty, ltp, st)
            except Exception as exc:
                logger.error("trade_dhan: BUY failed %s: %s", symbol, exc)
            time.sleep(0.5)

        if _error_counts:
            logger.info("trade_dhan: %s scan skip reasons: %s", strat_key, _error_counts)

        state[strat_key] = open_positions

    _save_state(state)
    _cycle_summary(state)
    logger.info("trade_dhan: cycle done — elite: %d, combo: %d",
                len(state.get("elite", {})), len(state.get("combo", {})))


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )
    run_trade_cycle()
